markdown: rdiscount
highlighter: rouge
permalink: :title
rdiscount:
extensions: [smart]
title :  NetBSD News
production_url : http://netbsd-news.me
local_url : http://localhost:4001
description: "A blog by Youri Mouton"
disqus_shortname: netbsd-news
analytics: UA-75092906-1
author :
  name : Youri Mouton
  github : nbyouri
  twitter : YouriMouton
  email: youri.mout@gmail.com
